### ISSUE TITLE
Hyundai login fails

### ISSUE THREAD

**Issue by jaroslawsky** [Hacksore/bluelinky#170]
**Describe the bug**
Instantiation of BlueLinky object not possible

**Usefull info(please complete the following information):**
 - OS: Windows
 - Bluelinky Version v7.6.0
 - Region: EU 

**Additional context**
The console output:

```
[2021-10-31 17:10:17] error: @EuropeController.login: sign in with EuropeanBrandAuthStrategy failed with error Error: @EuropeanBrandAuthStrategy.login: Cannot find login-actions code.
_ [ManagedBluelinkyError]: @EuropeController.login: [400] Bad Request on [POST] https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/signin - {"errId":"40be8673-ca44-43ec-81ad-9931baf582ca","errCode":"4003","errMsg":"Invalid values"}
    at R (C:\Projects\BlueLinkTest1\BlueLinkTest1\node_modules\bluelinky\dist\index.js:17:11678)
    at ie.<anonymous> (C:\Projects\BlueLinkTest1\BlueLinkTest1\node_modules\bluelinky\dist\index.js:17:39455)
    at Generator.throw (<anonymous>)
    at a (C:\Projects\BlueLinkTest1\BlueLinkTest1\node_modules\bluelinky\dist\index.js:17:136)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  source: GotError [HTTPError]: Response code 400 (Bad Request)
      at EventEmitter.<anonymous> (C:\Projects\BlueLinkTest1\BlueLinkTest1\node_modules\got\source\as-promise.js:74:19)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    host: 'prd.eu-ccapi.hyundai.com:8080',
    hostname: 'prd.eu-ccapi.hyundai.com',
    method: 'POST',
    path: '/api/v1/user/signin',
    socketPath: undefined,
    protocol: 'https:',
    url: 'https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/signin',
    gotOptions: {
      path: '/api/v1/user/signin',
      protocol: 'https:',
      slashes: true,
      auth: null,
      host: 'prd.eu-ccapi.hyundai.com:8080',
      port: '8080',
      hostname: 'prd.eu-ccapi.hyundai.com',
      hash: null,
      search: null,
      query: null,
      pathname: '/api/v1/user/signin',
      href: 'https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/signin',
      retry: [Object],
      headers: [Object],
      hooks: [Object],
      decompress: true,
      throwHttpErrors: true,
      followRedirect: true,
      stream: false,
      form: false,
      json: true,
      cache: false,
      useElectronNet: false,
      method: 'POST',
      body: '{"email":"info@********","password":"********"}',
      cookieJar: [CookieJar]
    },
    statusCode: 400,
    statusMessage: 'Bad Request',
    headers: {
      'ccsp-request-id': '40be8673-ca44-43ec-81ad-9931baf582ca',
      'ccsp-span-id': '4',
      'content-length': '92',
      'content-type': 'application/json',
      date: 'Sun, 31 Oct 2021 16:10:17 GMT',
      vary: 'Origin',
      'x-ratelimit-limit': '0',
      'x-ratelimit-remaining': '0',
      'x-ratelimit-reset': '0',
      connection: 'close'
    },
    body: {
      errId: '40be8673-ca44-43ec-81ad-9931baf582ca',
      errCode: '4003',
      errMsg: 'Invalid values'
    }
  }
}
```

**Comment by jaroslawsky** [comment]
This issue is different to "Kia login fails #143"

The error message here is:  Cannot find login-actions code.

**Comment by jaroslawsky** [comment]
Hey,

v7.6.1 with the changed newAuthClientId Guid works!!

Thank's a lot.

Perfect tool!

best regards,
Klaus
