### ISSUE TITLE
@EuropeControllerLogin: AuthCode was not found'

### ISSUE THREAD

**Issue by Sauwald** [Hacksore/bluelinky#70]
root@aec0b057cea3:/usr/local/lib/node_modules/bluelinky# node debug.js 
? What Region are you in? EU
{ region: 'EU' }
Logging in...
(node:6104) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('@EuropeControllerLogin: AuthCode was not found')
    at t.emit (events.js:187:17)
    at t.<anonymous> (/usr/local/lib/node_modules/bluelinky/dist/index.js:2:40208)
    at /usr/local/lib/node_modules/bluelinky/dist/index.js:2:1955
    at Object.throw (/usr/local/lib/node_modules/bluelinky/dist/index.js:2:2060)
    at a (/usr/local/lib/node_modules/bluelinky/dist/index.js:2:850)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Hacksore** [comment]
@Sauwald I was seeing this too with my test account but I don't have a car in EU to test it fully. Can you set `LOG_LEVEL=debug` and see if the verbose output helps us troubleshoot further?

**Comment by Sauwald** [comment]
root@aec0b057cea3:/usr/local/lib/node_modules/bluelinky# LOG_LEVEL=debug node debug.js 
? What Region are you in? EU
{ region: 'EU' }
Logging in...
[2020-09-15 05:00:56] debug: EU Controller created
[2020-09-15 05:00:56] debug: Bluelinky is logging in automatically, to disable use autoLogin: false
[2020-09-15 05:00:56] debug: loggin into to API
(node:6125) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('@EuropeControllerLogin: AuthCode was not found')
    at t.emit (events.js:187:17)
    at t.<anonymous> (/usr/local/lib/node_modules/bluelinky/dist/index.js:2:40208)
    at /usr/local/lib/node_modules/bluelinky/dist/index.js:2:1955
    at Object.throw (/usr/local/lib/node_modules/bluelinky/dist/index.js:2:2060)
    at a (/usr/local/lib/node_modules/bluelinky/dist/index.js:2:850)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6125) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6125) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by plips-nl** [comment]
I retested my Kia-fork today, no errors. I then compared my code with the bluelinky master.  Only difference is the europe/contants.ts file. 

[2020-09-15 09:23:07] debug: EU Controller created
[2020-09-15 09:23:07] debug: Bluelinky is logging in automatically, to disable use autoLogin: false
[2020-09-15 09:23:07] debug: loggin into to API
[2020-09-15 09:23:09] debug: EU Vehicle 1fa2<snip>b created
[2020-09-15 09:23:09] debug: Added vehicle 1fa<snip>b
[2020-09-15 09:23:09] debug: Found 1 on the account

**Comment by Sauwald** [comment]
Can I support in any other way to find the bug?

**Comment by Hacksore** [comment]
@Sauwald can you check out the code from the `develop` branch and try again. I added a debug log that might help us understand better.

**Comment by Sauwald** [comment]
root@aec0b057cea3:/home/node_modules/bluelinky# LOG_LEVEL=debug node debug.js
? What Region are you in? EU
{ region: 'EU' }
Logging in...
[2020-09-16 12:30:15] debug: EU Controller created
[2020-09-16 12:30:15] debug: Bluelinky is logging in automatically, to disable use autoLogin: false
[2020-09-16 12:30:15] debug: loggin into to API
[2020-09-16 12:30:17] debug: {
  "step": 5
}
(node:8165) UnhandledPromiseRejectionWarning: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('@EuropeControllerLogin: AuthCode was not found')

**Comment by Hacksore** [comment]
Yeah, that's exactly what I got with my test account 🤔. Not really sure what the response from the login means in this case.

```json
{
"step": 5
}
```

**Comment by Hacksore** [comment]
@Sauwald Actually I think I figured it out, it's forcing a password change. Go to this link and see if you get asked to change your password.

https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/oauth2/authorize?response_type=code&state=test&client_id=6d477c38-3ca4-4cf3-9557-2a1929a94654&redirect_uri=https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/oauth2/redirect

**Comment by Sauwald** [comment]
Yes, that is exactly what I just found out and wanted to write.
Now after changing the password via the app it works again.
Thanks.

**Comment by Hacksore** [comment]
I'd imagine now that we know what `step: 5` is we could add a better message in the error. I'm going to close this as there is nothing we can do to prevent it.
