### ISSUE TITLE
update() will give a error: 'TypeError: vehicle.update is not a function' 

### ISSUE THREAD

**Issue by MarkusKress** [Hacksore/bluelinky#78]
bluelink.js:
```
client.on('ready', async () => {
const vehicle = client.getVehicle('Txxxxxxxxxxxx3');
const response = await vehicle.update();
console.log(response);
});
```
fails with
```
node bluelink.js 
(node:11992) UnhandledPromiseRejectionWarning: TypeError: vehicle.update is not a function
    at t.client.on (/root/bluelink.js:30:32)
    at t.emit (events.js:198:13)
    at t.<anonymous> (/root/node_modules/bluelinky/dist/index.js:2:40989)
    at /root/node_modules/bluelinky/dist/index.js:2:1955
    at Object.next (/root/node_modules/bluelinky/dist/index.js:2:2060)
    at s (/root/node_modules/bluelinky/dist/index.js:2:799)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:11992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Hacksore** [comment]
You don't call `update` anymore as it's not a method that exists. Refreshing data from the vehicle is done at the method level.

ie. When you want the latest status it's `vehicle.status({ parsed: false, refresh: true })`
